export { default as Home } from "./Home/Home"
export { default as Menu } from "./Menu/Menu"
export { default as Company } from "./Company/Company"
export { default as Login } from "./Login/Login"
export { default as Order } from "./Order/Order"
